export const TIPOS_ACTIVIDAD_VOLUNTARIADO: readonly string[] = [
  'Accompañamiento a personas mayores',
  'Alfabetización y educación popular',
  'Apoyo escolar y tareas dirigidas',
  'Arte, cultura y talleres creativos',
  'Atención en merenderos y comedores comunitarios',
  'Campañas de concientización',
  'Cocina / logística',
  'Comunicación, diseño y redes sociales',
  'Cuidado de niños, niñas y adolescentes',
  'Deporte, recreación y actividades al aire libre',
  'Defensa de derechos y acompañamiento legal básico',
  'Emergencias y operativos solidarios',
  'Huertas urbanas y agricultura social',
  'Informática y alfabetización digital',
  'Interpretación y traducción',
  'Logística, depósito y distribución',
  'Mantenimiento, pintura y refacción',
  'Medio ambiente y limpieza de espacios públicos',
  'Música, teatro y eventos comunitarios',
  'Recaudación de fondos y voluntariado administrativo',
  'Reforestación y trabajo al aire libre',
  'Salud comunitaria y primeros auxilios',
  'Trabajo al aire libre',
  'Visitas domiciliarias y contención social',
  'Voluntariado en hospitales y centros de salud',
  'Voluntariado con animales y refugios',
  'Otra (detallar en descripción o requisitos)',
];